export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const LIKE_POST = 'LIKE_POST';
export const AUTH = 'AUTH';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const COMMENT_POST = 'COMMENT_POST';

export const FETCH_USER = 'FETCH_USER'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const FETCH_USER_PRODUCTS = 'FETCH_USER_PRODUCTS';

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';


export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const FETCH_CAROUSELS = 'FETCH_CAROUSELS'


export const ADD_TO_CART_LOCAL = 'ADD_TO_CART_LOCAL';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAIL = 'FETCH_CART_FAIL';
export const MERGE_CART_SUCCESS = 'MERGE_CART_SUCCESS';